"""empty message

Revision ID: 3955ed96ddea
Revises: adba088e1b8f
Create Date: 2018-10-25 15:11:09.215937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3955ed96ddea'
down_revision = 'adba088e1b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('createdatetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'createdatetime')
    # ### end Alembic commands ###
