"""empty message

Revision ID: 41f2bc298cd0
Revises: 3955ed96ddea
Create Date: 2018-11-15 15:54:14.821752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f2bc298cd0'
down_revision = '3955ed96ddea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'company', ['company'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company')
    # ### end Alembic commands ###
