"""empty message

Revision ID: c1ea117506ec
Revises: 
Create Date: 2018-10-25 00:22:00.627020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ea117506ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('wxid', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=1), nullable=True),
    sa.Column('createdatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
